name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
      with:
        allow-checksums: a5e75118d96b4eac2100876f6af6a5ca5029cd440f87736425350fb4cf308b42

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: false

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode debug keystore
      run: base64 -d debug.keystore.base64 > debug.keystore || echo "No base64 keystore found, skipping..."

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
